//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiTrafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Courses = new HashSet<Cours>();
            this.Periodic_Courses = new HashSet<Periodic_Courses>();
        }
    
        public int ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string PHONE { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual ICollection<Periodic_Courses> Periodic_Courses { get; set; }
    }
}
