//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiTrafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int ID { get; set; }
        public System.DateTime STARTING_DAY { get; set; }
        public System.TimeSpan STARTING_TIME { get; set; }
        public string STARTING_ADDRESS { get; set; }
        public string ARRIVAL_ADDRESS { get; set; }
        public Nullable<System.DateTime> ARRIVAL_TIME { get; set; }
        public int client_ID { get; set; }
        public Nullable<int> taxi_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Taxi Taxi { get; set; }
    }
}
