//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiTrafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public Taxi()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int ID { get; set; }
        public string MATRICULE { get; set; }
        public string TYPE { get; set; }
        public int driver_ID { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual User User { get; set; }
    }
}
